// Package notes is the core data layer for NeuronCLI. This file is intentionally
// minimal — the Note type and Store implementation live in parser.go and store.go
// respectively, both of which were generated by the full implementation pass.
package notes
